### ISSUE TITLE
Images do not appear in Android v6.0 Gallery

### ISSUE THREAD

**Issue by jasonkhanlar** [yellowbluesky/PixivforMuzei3#119]
I have been searching for how come the images downloaded by Pixiv for Muvei3 do not appear in the default Android 6.0 gallery app.

I tried solutions suggested in https://android.stackexchange.com/questions/55967/pictures-and-videos-not-showing-in-the-gallery

and I noticed that from the File Manager, when I tapped on an image file and opened it in the gallery, then FINALLY an entry appeared in the Gallery app for that directory, and all the images appeared. Unfortunately I have since learned that ONLY the images that existed in that directory when I did that appear in the Gallery app listing. All the new images added to the directory after, they do not appear, and even after I tried to clear and reset cache, and other things, still I wasn't able to get any of the new images to appear. And I don't want to do that every time anyway.

but just today I glanced at https://stackoverflow.com/questions/11803329/android-photo-gallery-not-updating-with-new-photos

and I thought maybe it's because the Muvie 3 app or the Pixiv for Muvei 3 plugin is missing code to send a signal to Android v6 to synchronize the gallery with new images?

My relevant Pixiv for Muzei 3 Settings:

Advanced Settings
-> Enable: Save pictures into external storage (it actually saves to the internal storage, not the external micro sd card I have in my phone)

That creates the directory on my phone: /storage/emulated/0/Pictures/PixivForMuzei3
and all the images are in there

Oh also as a side now, when I look at the files in the directory, I see a LOT of duplicate redundant images in pairs. The same artworks in two different files, one is .jpg, the other is .png and also with timestamps that are far apart which probably suggests that they are from different Pixiv API queries, and treated as different artworks/files, even though they are the same art, just different image file format encoding.

**Comment by yellowbluesky** [comment]
Hi, thanks for your thorough investigation. For reference, my setup is Lineage OS based ROM, Android 10 and Android 9.

> images downloaded by Pixiv for Muvei3 do not appear in the default Android 6.0 gallery app. 

I've never had this happen on my configurations. However I will implement the fixes suggested in the StackOverflow pages.

> it actually saves to the internal storage, not the external micro sd card I have in my phone

This is the "correct" behavior, I got a bit lazy and hardcoded in the path to the current storage location. Let me know if you want me to work on allowing the user to select any storage location they want.

> I see a LOT of duplicate redundant images in pairs. The same artworks in two different files, one is .jpg, the other is .png

This is quite odd, I've got code that specifically checks if the file in either image format exists, and then download only if neither exist. I'll investigate this

**Comment by yellowbluesky** [comment]
I think I know whats going on with the duplicate artworks you're seeing:

- Most of the pngs your're seeing are from this apps private cache at /storage/emulated/0/Android/data/com.antony.muzei.pixiv/
The artworks in this folder are transient, they get deleted regularly either by the user ("Immediately clear image cache" button) or by the Android system (automatic cache clearing). The artworks here are used as backing for Muzei, meaning these are the images that get actually shown

- If you have the option selected to do so, then a second copy of artworks are saved into /storage/emulated/0/Pictures/PixivForMuzei3. The artworks here have the correct file extension, and persist no matter what the user or the Android system does to my app's cache.

**Comment by yellowbluesky** [comment]
Fixed in 0c391bcbc85b40e42595441c850adfe9484eec4d

**Comment by jasonkhanlar** [comment]
"Let me know if you want me to work on allowing the user to select any storage location they want."

It isn't TOO important, but my phone has 32GB internal storage, and I'm using 128GB micro-sd card, but I think my phone supports up to 512GB micro sd, or  maybe 2TB, but I never tried higher yet. And before using Muvei 3 my phone storage tends to fill up quickly anyway from other activities, so it would be convenient to use micro sd, but that is not an urgent important concern, just a bonus! <3
