### ISSUE TITLE
Allow storage of artwork onto SD cards

### ISSUE THREAD

**Issue by yellowbluesky** [yellowbluesky/PixivforMuzei3#120]
A user expressed their desire for this feature in https://github.com/yellowbluesky/PixivforMuzei3/issues/119#issuecomment-657759319

**Comment by yellowbluesky** [comment]
Option for Android 10 and above devices added in 98b282ac4a23f34f277e6d91916182fd13a129c8

**Comment by yellowbluesky** [comment]
it is not possible to saave files to external storage on Android 10 or lower. See [this stackoverflow](https://stackoverflow.com/a/51385515) for more details.

**Comment by jasonkhanlar** [comment]
I have used several apps that have provided selection capabilities to save to 2ndary micro sd cards inserted int my LG G4 Android 6.0 phone.

https://developer.android.com/training/data-storage indicates Android 4.4 and higher support app-specific files on external storage.

https://stackoverflow.com/questions/7887078/android-saving-file-to-external-storage/7887114#7887114 mentions

```Environment.getExternalStorageDirectory()```

https://stackoverflow.com/questions/7887078/android-saving-file-to-external-storage/21191262#21191262 mentions

```Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)```

**Comment by yellowbluesky** [comment]
Thanks for your research!

The documentation is terminology is rather confusing with regards to what is and isn't external storage. Using a phone with 32GB of flash storage as an example:
- Internal storage is the system partition and application private storage. This takes up about 8GB of space on the flash storage.
- External storage is everything the user can freely access and modify. This is both the phone's flash storage (the 24GB remaining after system reserved mounted at /storage/emulated/0) and the SD card.

All the methods used in the documentation you linked (for example `Environment.getExternalStorageDirectory()` and its variants) returns a path onto the phones flash storage.

In order to get a path that will lead me to the SD card, I need to build it up myself by getting a list of mounted volumes and then manually constructing a hard coded path from that. Even when, I end up with an exception whenever I try to use that path that looks like this 
`Exception: External path: /storage/0123-4567/Test/123.txt: Neither user 10196 nor current process has android.permission.WRITE_MEDIA_STORAGE.`

There is a way around, but it involves asking users to:

- Navigate to exactly the path they want me to save their pictures to. I'm not fond of this idea, because it relies too much on the user.

- Give me read and write permissions to their entire SD card. I prefer this, but I don't like the security implications of giving my app complete control.
