### ISSUE TITLE
Filters not work

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#124]
I'm not sure but it seems that some filters don't work anymore in 3.1.2.
I set the ratio filter to Portrait but some wide images slide in, e.g. https://www.pixiv.net/artworks/83386137 and https://www.pixiv.net/artworks/83361169. More manga than before slide in when I disable it. Maybe the NSFW filter is also broken.

**Comment by yellowbluesky** [comment]
Thanks for letting me know about this

I'll try to work on this over the weekend

BTW, those are some nice artworks

**Comment by yellowbluesky** [comment]
I'm looking at this issue now

**Comment by linsui** [comment]
Thanks!

**Comment by Kyle2142** [comment]
Based on title I'm commenting rather than creating new issue: include/exclude manga option does not seem to make a difference. 
Another similar open source app on play store seems to implement this well. 
It's nice that we can delete them now, but obviously we'd prefer to not get them in the first place.
I am using daily ranking, if that matters

**Comment by yellowbluesky** [comment]
I really can't answer why manga keep slipping through.

There's only one flag that sets whether or not an image is manga; [illust_type for Ranking](https://github.com/yellowbluesky/PixivforMuzei3/blob/920d59d5cdd4b2076663f224eb84bd958b247005/app/src/main/java/com/antony/muzei/pixiv/provider/PixivArtWorker.kt#L463), and [type for Feed.](https://github.com/yellowbluesky/PixivforMuzei3/blob/920d59d5cdd4b2076663f224eb84bd958b247005/app/src/main/java/com/antony/muzei/pixiv/provider/PixivArtWorker.kt#L601)

I'm very very sure I've got the logic correct.

**Comment by linsui** [comment]
It seems that the problem is not about manga but the whole filter. The NSFW filter and Portrait filter also don't work anymore. [Here](https://www.pixiv.net/artworks/86344083) is a manga that slip through, could you please check it? Thanks!

**Comment by yellowbluesky** [comment]
When you say NSFW filter doesn't work, on what mode are you talking about? Rankings, Feed, or both?

**Comment by linsui** [comment]
Daily ranking.  E.g., no matter I set the filter to SFW or NSFW I can see this one. https://www.pixiv.net/member_illust.php?mode=medium&illust_id=86361285

**Comment by yellowbluesky** [comment]
Hi Linsui

![image](https://user-images.githubusercontent.com/11283778/102711970-b380cd80-4311-11eb-8db4-14e6d2d3e290.png)
I've confirmed manga filtering to be working now https://www.pixiv.net/en/artworks/86344083

![image](https://user-images.githubusercontent.com/11283778/102712014-0c506600-4312-11eb-9c69-a5351da8ee62.png)
I've also confirmed that NSFW filtering to be working. https://www.pixiv.net/en/artworks/86361285

I'll test some more things out, then I'll it out as a new build.

Thanks @Kyle2142 and @linsui for helping and persisting in providing feedback.

**Comment by linsui** [comment]
Thanks!

**Comment by yellowbluesky** [comment]
I've pushed 3.1.4 out into release.

I've corrected a number of logic errors that were rejecting valid images (NSFW levels), and letting in invalid images (manga).

Again, thanks to you two, for getting me back into programming. I was feeling a bit burnt out from work and programming in general, now I'm getting back I'm genuinely enjoying it again :D

**Comment by linsui** [comment]
It works perfectly! Thanks! The aspect ratio fileter alse works well! I guess I can close this issue.
