### ISSUE TITLE
Added to bookmark does not work

### ISSUE THREAD

**Issue by L4rue** [yellowbluesky/PixivforMuzei3#125]
After i upgrade the Muzei，i found the function of adding to bookmark doesn't work.
In order to verify this problem, I tested the old version of Muzei with an old phone，it works，but after i upgrade again，it doesn't work。
Maybe the muzei have change something.

**Comment by yellowbluesky** [comment]
Hi, thanks for your issue report

Muzei 3.4.0 changed how custom commands work, and I've been having some difficulty in getting "Add to Bookmark" working again. 

I've been fairly busy recently, but I'll try to work on this issue, I enjoyed using it too

**Comment by yellowbluesky** [comment]
Hi there,

Thanks for your patience, this fix took me auite a while to get around to, I started a new job and took a break from Open Source.

This issue has been fixed in e0f7ad7e0a49a68aa98a7154ccd0a7cac66098a9

Expect to see a build go out in the next few days :)

**Comment by L4rue** [comment]
Long time no see.
I'm glad to see the bug fixed.
Thank you very much for your hard work.
