### ISSUE TITLE
Centering the image

### ISSUE THREAD

**Issue by rain1273** [yellowbluesky/PixivforMuzei3#130]
I would love to see a feature that allows to disable wallpaper scrolling i.e. the ability to choose where to center the image.

**Comment by yellowbluesky** [comment]
HI there, thanks for your suggestion

Unfortunately, I don't believe that my app can help you with this. You will need to chase the developer of [Muzei](https://github.com/romannurik/muzei)

All my app does is provide to Muzei an image to display. Muzei is the app that controls the display and scrolling of images.

**Comment by rain1273** [comment]
I understand. Thank you for your answer. Good luck!
