### ISSUE TITLE
Can't share on 10

### ISSUE THREAD

**Issue by SettingDust** [yellowbluesky/PixivforMuzei3#132]
Feedback to Muzei
> iQOO Neo3, Android 10, Pixiv for Muzei 3. Can't share current wallpaper

Muzei Developer:
> This issue is due to Pixiv using an old version of the Muzei API as this exact issue with commands like share not working on Android 10+ is fixed in Muzei API 3.4 (https://github.com/romannurik/muzei/releases/tag/api3.4.0). You should send feedback directly to Pixiv to upgrade to the latest API.

**Comment by yellowbluesky** [comment]
I did indeed update my commands to use the new API introduced in Muzei 3.4

Sharing is working fine on my phone; I'm running Lineage OS based on Android 10. I tested it again literally just now.

I've not touched that section of code in a while, so nothing comes to mind as to why it doesn't work.
I'll investigate this issue more thoroughly when I have time in the near future.

**Comment by SettingDust** [comment]
> 
> 
> I did indeed update my commands to use the new API introduced in Muzei 3.4
> 
> Sharing is working fine on my phone; I'm running Lineage OS based on Android 10. I tested it again literally just now.
> 
> I've not touched that section of code in a while, so nothing comes to mind as to why it doesn't work.
> I'll investigate this issue more thoroughly when I have time in the near future.

How can I get the logs?

**Comment by SettingDust** [comment]
Sorry, the share is ok now. I don't know why.
Where is the bookmarked images.
And I can't view artwork details

**Comment by yellowbluesky** [comment]
Hi, sorry again about this slow response

There are two places where you can open artwork details:

- Clicking on artwork information in Muzei

- Clicking on the three-dot overflow menu, and selecting "Show details" (top option)

Do neither of those not work for you?

**Comment by SettingDust** [comment]
> Hi, sorry again about this slow response
> 
> There are two places where you can open artwork details:
> 
> * Clicking on artwork information in Muzei
> * Clicking on the three-dot overflow menu, and selecting "Show details" (top option)
> 
> Do neither of those not work for you?
 
First is ok. Second useless
