### ISSUE TITLE
SSLCertificateSocketFactory is deprecated，please update

### ISSUE THREAD

**Issue by Orca-web** [yellowbluesky/PixivforMuzei3#140]
![image](https://user-images.githubusercontent.com/59247295/105525814-882c3c80-5d1c-11eb-8e29-f2aaac726046.png)

**Comment by yellowbluesky** [comment]
Hey there,

SSLCertificateSocketFactory is required for the China SNI Bypass. It doesn't work anymore, and I'm due to update that part of the code, so I might remove it soon/

Other than that, is there a compelling reason to remove the use of this deprecated library?
