### ISSUE TITLE
Feature request: provide a switch to disable download artworks in mobile network

### ISSUE THREAD

**Issue by KawaiiZapic** [yellowbluesky/PixivforMuzei3#144]
Muzei only provides a switch to disable images switching.   
But this way cannot switch images in any network and only download images in WiFi.   

** I found this app spent 3 GB of my mobile data network and nearly run out my mobile data network.

**Comment by yellowbluesky** [comment]
- The Muzei "Auto advance only on Wi-Fi" option stops the current wallpaper from changing
- You would like for the wallpaper to cycle through already downloaded artworks when on mobile data?

Sure things, I'll try to put it in

**Comment by yellowbluesky** [comment]
Feature added in a97091c7719b5ee72b0a274c32fcefadf79e549f

**Comment by yellowbluesky** [comment]
Hi there, this feature has been pushed out to production version 3.3.0, you can expect to download it very soon.

Thank you for this suggestion!
