### ISSUE TITLE
Bug: Some partial-downloaded artworks is saved in storage

### ISSUE THREAD

**Issue by KawaiiZapic** [yellowbluesky/PixivforMuzei3#151]
For network reason, sometime artworks cannot download completely.  
But these partial-downloaded images will be keep in storage, not delete or continue to download.   
And they will not appear in images list in Muzei,just like is not existed.   
  
P.S: I enabled save to public storage and auto copping image, I can't ensure cause this by them or not.

![A partial-downloaded artwork](https://user-images.githubusercontent.com/45936772/111915063-7ca48a00-8aaf-11eb-89a3-f45d3915e28d.png)

**Comment by yellowbluesky** [comment]
What version of Android are you on?

I know exactly what is causing this issue, I had it fixed earlier, but I disabled it again out of laziness.

However, if you're on Android 10 or higher you're going to have to live with it for a little bit until I put some time into fixing this, I'm afraid

**Comment by misternem0** [comment]
I have this issue as well from time to time. I have it set to download 3 images at a time, and the images (from bookmarks) rotate once per hour. I will see partially downloaded images perhaps once or twice every day or two.

**Comment by Navixer** [comment]
![Screenshot_20240131_113911_Gallery](https://github.com/yellowbluesky/PixivforMuzei3/assets/23425892/1b7aa773-af9c-4319-b8ab-7310ffbbab85)
It's getting worse. Almost all recently downloaded images are partial or corrupted. I'm on Samsung A52s One Ui 6.

**Comment by yellowbluesky** [comment]
Thanks for sending through a other issue report 

This is being worked on tracked in issue #199. 

A fix is close to release actually, I am just ironing out one last bug with the implementation.

If possible, can you please send me samples of two or three corrupted images?

Part of the difficulty in fixing this issue is that I cannot replicate this issue from my location (Central Europe)

**Comment by Navixer** [comment]
https://drive.google.com/file/d/1DPRVNpJYaexL4slcbQLw9hAaOkDTzIYQ/view?usp=sharing
Here you go. I archived them so they aren't modified. 
Thanks for working on it, I really appreciate it.

**Comment by yellowbluesky** [comment]
Actually, can you please try this test build and let me know how well it works for you?

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.1.7-alpha

This will install a new app and new Muzei source that must be selected.

**Comment by Navixer** [comment]
Okay I will try and report back soon.

**Comment by Navixer** [comment]
![Screenshot_20240131_123558_My Files](https://github.com/yellowbluesky/PixivforMuzei3/assets/23425892/8e8b67a7-8685-44d5-8021-8f7888c8935c)
Now it saves a 0 byte empty file. When I turn on the save to storage setting the app can't fetch any pictures (it gets files but they are empty and can't apply them) 

![Screenshot_20240131_123433_Muzei](https://github.com/yellowbluesky/PixivforMuzei3/assets/23425892/ca31cddf-e918-4e5b-8ca7-cb91a21600e8)
When I turn the setting off it correctly gets pictures and applies them but ofc now there are no saved pics.

**Comment by yellowbluesky** [comment]
The other user reported a similar issue to you.

Can you please tell me what Android version and skin your phone is running?

**Comment by Navixer** [comment]
Android 14. Samsung One UI 6. There is no skin, I only have a font. The bug has been here for a long time I don't think it's related to customization. It was here on android 13 and One UI 5 too. I also use Good Lock (home up etc.) 
I have just reverted the font to original and the same thing happens. Empty images (dev version).

**Comment by yellowbluesky** [comment]
Can you please try this build and let me know if you have any issues with it.

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.1.7-alpha2

After uninstalling and reinstalling my app, I was able to replicate your issue of not being able to save into external storage.
Turns out the issue was a very simple one and entirely my fault.

**Comment by Navixer** [comment]
It seems like everything is fixed! It properly saves now and there is no partial or corrupted images. I tried it with 10 images no issues so far. Don't worry about it, thanks for the good work.

**Comment by yellowbluesky** [comment]
No worries, I'm happy to help my users :)

I'll close this issue now. When the fix gets merged into the production version on Google Play or Fdroid I will let you know here
