### ISSUE TITLE
Can't login?

### ISSUE THREAD

**Issue by SettingDust** [yellowbluesky/PixivforMuzei3#155]
Logged in browser, but navigation to account manage page crashed.
![](https://i.imgur.com/ENYphtJ.jpg)

Crashed after clicked the first button.

**Comment by yellowbluesky** [comment]
Thanks for bringing this to my attention, I'll take a look

**Comment by yellowbluesky** [comment]
What version of Android are you on?

**Comment by SettingDust** [comment]
> What version of Android are you on?

11
Updated about a month.

**Comment by yellowbluesky** [comment]
Can you describe to me exactly what you do and exactly what happens?
It's normal for the screen to turn white and then return to my app's main page once you have pressed the first button

A screen recording would be very helpful if you can create and upload one.

**Comment by SettingDust** [comment]
> Can you describe to me exactly what you do and exactly what happens?
> 
> A screen recording would be very helpful if you can create and upload one.
> 
> It's normal for the screen to turn white and then return to my app's main page once you have pressed the first button
> 
> I too am on Android 11 (MIUI 12) and ASOP 11

I don't know how to catch crash log without root & xposed. It's crashed.

**Comment by SettingDust** [comment]
Wait for a moment. Recording

**Comment by SettingDust** [comment]
https://ws28.cn/f/5chxz44yf8o

**Comment by yellowbluesky** [comment]
yes I can, watching it now :)

**Comment by SettingDust** [comment]
> yes I can, watching it now :)

In fact. It's just crashed after clicking XD.

**Comment by yellowbluesky** [comment]
I have an idea for what it could be, but I'll need to investigate and experiment some.

I'll get back to you later with more information or request for information.

**Comment by SettingDust** [comment]
> I have an idea for what it could be, but I'll need to investigate and experiment some.
> 
> I'll get back to you later with more information or request for information.

Okay, thanks a lot

**Comment by yellowbluesky** [comment]
The app is getting stuck because the server response is indicating an error.
This is odd, because there is no problem with credentials; you login using the "Continue with existing account" option

Tomorrow I'll provide a build that includes a way for you to send me a copy of the server response

**Comment by yellowbluesky** [comment]
Hi there, can you try install this build and then try logging in?

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3

The server response is automatically uploaded to my pastebin.

Full disclosure, your access token and refresh token may be revealed to me. I promise to not do anything with them, I have my own account :)

This took me a bit longer than I expected, because of Android Studio updating and changing some settings around.

**Comment by SettingDust** [comment]
> Hi there, can you try install this build and then try logging in?
> 
> https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3
> 
> The server response is automatically uploaded to my pastebin.
> 
> Full disclosure, your access token and refresh token may be revealed to me. I promise to not do anything with them, I have my own account :)
> 
> This took me a bit longer than I expected, because of Android Studio updating and changing some settings around.

Tried times

**Comment by yellowbluesky** [comment]
Still crashing?

Well this is awkward, cos I don't see any pastes in my pastebin, i might have set something up wrong :(

**Comment by yellowbluesky** [comment]
Hi there,

A server response log did eventually show up. There is no error, you login just fine.

Can you try this build please? I had added some code that more gracefully closes the login WebView Activity.
https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.1

As a disclaimer, the logging code is still present, let me know if you would rather I remove it immediately.

**Comment by SettingDust** [comment]
> Still crashing?
> 
> Well this is awkward, cos I don't see any pastes in my pastebin, i might have set something up wrong :(

Gotcha

**Comment by yellowbluesky** [comment]
Ok, I'm hitting the limits of what I can do without having access to logs of some kind.

I'll produce a build that will automatically upload logcat logs for this app to pastebin.

Thanks for your patience in this, I know how frustrating not being able to log in is, and you've always been very good to me and this app

**Comment by SettingDust** [comment]
Haven't uninstall before install newest version. Tried after you say that. Same result. :D
It's ok. In my view, you should be the one get frustrating. So, what I have is gratitude

**Comment by SettingDust** [comment]
Btw, the version that translated Night Mode haven't released

**Comment by yellowbluesky** [comment]
This time lucky I hope

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.2

I removed Kotlin coroutines, and replaced them with traditional Threads and Runnables.

**Comment by SettingDust** [comment]
> This time lucky I hope
> 
> https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.2
> 
> I removed Kotlin coroutines, and replaced them with traditional Threads and Runnables.

Tried, crashed. Isn't there a way to export log?

**Comment by SettingDust** [comment]
I can login with https://github.com/james58899/MuzeiPixivSource. It's seems that it's won't navigate to another page after login.

Maybe @james58899 can give some advice?

**Comment by james58899** [comment]
> 
> 
> I can login with https://github.com/james58899/MuzeiPixivSource. It's seems that it's won't navigate to another page after login.
> 
> Maybe @james58899 can give some advice?

Try connect to computer and using `adb logcat` to get crash stacktrace.

I can also login successfully on both apps.

**Comment by SettingDust** [comment]
> > 
> > 
> > I can login with https://github.com/james58899/MuzeiPixivSource. It's seems that it's won't navigate to another page after login.
> > 
> > Maybe @james58899 can give some advice?
> 
> Try connect to computer and using `adb logcat` to get crash stacktrace.
> 
> I can also login successfully on both apps.

Okay

**Comment by SettingDust** [comment]
![image](https://user-images.githubusercontent.com/19922286/118211701-17fa2000-b49f-11eb-8b65-1902d2ed39fc.png)

I'm done!

**Comment by yellowbluesky** [comment]
Hello there,

Can you please try this build?
https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.3

From the logcat you posted, my CustomClientHeaderInterceptor was causing a hang in the networking library.
This interceptor was necessary under the old login and authentication scheme.

I tested it myself, and I can still login fine without the interceptor.
To be honest, I still don't know why only you were having this why

let me know how it goes

@SettingDust thank you for taking the time to get the logcat for me
@james58899 thank you for your time in trying my app out and helping SettingDust out, and also thank you for having high quality code available for my reference.

**Comment by SettingDust** [comment]
New stacktrace.

![image](https://user-images.githubusercontent.com/19922286/118273837-03e20d00-b4f7-11eb-89a1-1b8ac352a860.png)

**Comment by SettingDust** [comment]
> I tested it myself, and I can still login fine without the interceptor.
> To be honest, I still don't know why only you were having this why

In fact, me too. I can login with any other app to pixiv. Such as @james58899's

**Comment by yellowbluesky** [comment]
From the latest logcat, your configuration seems to external function calls that do networking

At this point, I've almost completely eliminated all such function calls, hopefully this will do the trick. 

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.4.1

**Comment by SettingDust** [comment]
> From the latest logcat, your configuration seems to external function calls that do networking
> 
> At this point, I've almost completely eliminated all such function calls, hopefully this will do the trick. 
> 
> https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.4.1

Okay!

**Comment by SettingDust** [comment]
It's can't download artworks. It's seems that a network problem. But I can use any other pixiv app and pixiv.net in browser. Weird :(

![image](https://user-images.githubusercontent.com/19922286/118485315-d9888d80-b74a-11eb-8fe0-c6d02ae22269.png)

**Comment by yellowbluesky** [comment]
Thanks for your patience while we work through this

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.5

let me know how this goes

I've increased the OkHttp timeouts and refreshed some networking code. I'm hoping that this will fix it, I'm hesitant to remove all interceptors like we did for LoginActivityWebview; this will complicate the code and make it harder to maintain.

If you still get errors, could you please provide logcats for both a ranking mode and a logged in mode?

**Comment by SettingDust** [comment]
Dayily:
![image](https://user-images.githubusercontent.com/19922286/118651352-0787d380-b818-11eb-92eb-f7ccbbab1113.png)

Logged Recommend
![image](https://user-images.githubusercontent.com/19922286/118652548-4bc7a380-b819-11eb-8edb-bcdae49f9e30.png)

**Comment by SettingDust** [comment]
I think it's not problem about the code in getArtwork. It's seems like a problem with network. But it's not. 
I can login in with this app and open any image in browser or other app.

**Comment by SettingDust** [comment]
Ooooop!

**Comment by yellowbluesky** [comment]
The latest set of errors, in particular "\n not found" is quite unusual, there aren't many search hits for this error code

In the latest build I've disabled gzip compression of the JSON for both ranking modes and auth modes, this was the recommended fix ok the official okhttp repo.

Let me know if this works

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.7

**Comment by SettingDust** [comment]
> The latest set of errors, in particular "\n not found" is quite unusual, there aren't many search hits for this error code
> 
> In the latest build I've disabled gzip compression of the JSON for both ranking modes and auth modes, this was the recommended fix ok the official okhttp repo.
> 
> Let me know if this works
> 
> https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.7

Same stack

**Comment by SettingDust** [comment]
I've searched for this. https://github.com/square/okhttp/issues/5390#issuecomment-610001882
I think the reason is server close the connection. But why?

**Comment by SettingDust** [comment]
Wait. It's weird. It's seems ok. WTF?
I close the VPN and it's download images with any mode.
But why? It should download normally with vpn like any other app. Strangely

**Comment by yellowbluesky** [comment]
> I've searched for this. [square/okhttp#5390 (comment)](https://github.com/square/okhttp/issues/5390#issuecomment-610001882)
> I think the reason is server close the connection. But why?

I already do this, I set retryOnConnectionFailure to true
https://github.com/yellowbluesky/PixivforMuzei3/blob/master/app/src/main/java/com/antony/muzei/pixiv/provider/network/OkHttpSingleton.kt#L34

> Wait. It's weird. It's seems ok. WTF?
> I close the VPN and it's download images with any mode.
> But why? It should download normally with vpn like any other app. Strangely

Did you try closing your VPN in any of the previous builds

Glad to hear that its working normally for you however :)

**Comment by SettingDust** [comment]
> Did you try closing your VPN in any of the previous builds

Haven't.
#160 try to don't use bypass  sni always. Maybe it is the reason why can't proxy work.

**Comment by yellowbluesky** [comment]
Hi there, can you please try build 3.4.3.4.1 with VPN off, and let me know if ranking artwork can be downloaded?
I'm not happy with the changes made, if we do not need them the better

You may have to uninstall your current app version, as Android complains if you downgrade an app.

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.4.1

I'm working on adding a toggle to the settings that enables or disables the SNI bypass, incorporating #160

**Comment by SettingDust** [comment]
Tried. I can download images without proxy and login in daily. And I can download with proxy with login in recommend mode.

**Comment by yellowbluesky** [comment]
Fantastic, thank you very much for your time helping me, I really appreciate it

I'll try to get a build out tonight or tomorrow

**Comment by yellowbluesky** [comment]
One more thing sorry, does 3.4.3.3 work when VPN is disabled?

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.3

**Comment by SettingDust** [comment]
> One more thing sorry, does 3.4.3.3 work when VPN is disabled?
> 
> https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.4.3.3

Yes. Downloaded images with daily mode without proxy and crashed when login

**Comment by yellowbluesky** [comment]
Ok, thank you to everyone who helped on this issue.

I believe it to be fixed, and I've pushed it out to production. Expect to see 3.4.3.8 in the Play Store or F-Droid in teh coming days, or download it now from the Github.
