### ISSUE TITLE
Strings in 'App settings can't be translated

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#158]
I didn't found them in strings.xml

**Comment by yellowbluesky** [comment]
Hello, I've extracted all the strings.
There are five strings that I would really appreciate if you could help translate them. They can be found at the bottom of here

https://github.com/yellowbluesky/PixivforMuzei3/blob/26797e01d099ae616c5e3e910a9fed75b9e08a4e/app/src/main/res/values-zh/strings.xml

**Comment by linsui** [comment]
Done!
