### ISSUE TITLE
Is it possible not to use WorkManager?

### ISSUE THREAD

**Issue by mslxl** [yellowbluesky/PixivforMuzei3#165]
I think [here](https://github.com/yellowbluesky/PixivforMuzei3/blob/728f442efdb77e1d2430d5be7f635760259027a9/app/src/main/java/com/antony/muzei/pixiv/provider/PixivArtWorker.kt#L95) should not use `WorkManager`.
`WorkManager` would not be run immediately sometimes but refresh action should be an immediate action. By using `WorkManager`,  load work wound not start after the `refresh` button was clicked, sometimes it needs to wait a long time to start the work. It will cause trouble when using and debugging the app.
Is it possible not to use WorkManager?

**Comment by yellowbluesky** [comment]
Pressing the button to "clear the cache and immediately download new artwork" does clear the WorkManager queue

https://github.com/yellowbluesky/PixivforMuzei3/blob/9fddaf67abb8d1a0766ebaa2105fe396b61e121c/app/src/main/java/com/antony/muzei/pixiv/settings/fragments/MainPreferenceFragment.kt#L155
