### ISSUE TITLE
Downloader is going haywire and downloading the same image multiple times

### ISSUE THREAD

**Issue by biomatter** [yellowbluesky/PixivforMuzei3#174]
![Screenshot_20211122-152722](https://user-images.githubusercontent.com/9300141/142954719-1a3e448c-601e-44fe-8275-bca546b59a2a.jpg)

Please see attached image as an example. This only started happening within the last few days. The image previewer in the app does not show the duplicates, hiding the problem

**Comment by yellowbluesky** [comment]
Hi there, what version of Android are you using?

**Comment by biomatter** [comment]
I'm on Android version 10. Thanks for being so fast, I really like the app

**Comment by yellowbluesky** [comment]
This is more for my curiosity, but can you please try setting each duplicate to be your wallpaper and then check if the same wallpaper is applied each time? Muzei sometimes bugs out its thumbnails, perhaps causing the issue you are having now.

Do you have the cache set to clear every day? If not, can you please try clearing the cache and then report back to me again tomorrow?

I am not sure why this issue has started happening recently / after the latest app update. The code that handles duplicate image detection was not touched, and has not been touched for many months now.

**Comment by biomatter** [comment]
Those aren't muzei thumbnails, that was a view from a photo viewing app. The duplicates were real, essentially.

I don't have it set to clear cache. Will that delete the contents of the folder?

**Comment by yellowbluesky** [comment]
Yes, clearing the cache (etiher by pressing the button on the Main tab or by enabling the automatic option) will clear all the images you have in there.

FYI, note that because you are not storing into external storage, the Android system may clear that folder at any time if it feels like it needs to reclaim space.

**Comment by biomatter** [comment]
Sorry, I was wrong... It is duplicates being saved into external storage, not the cache. I didn't understand the difference and thought that the pixiv folder was the one the app used. My bad :(
