### ISSUE TITLE
It doesn't retry failed build

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#199]
In previous versions it retry the downloading when the downloaded file is broken. But in the latest version it doesn't retry anymore and show the broken images directly.

**Comment by yellowbluesky** [comment]
I've figured out a better and more efficient way to check for incomplete or corrupt images.

The old way was very inefficent and often did not work.

I will try to add this feature in the near future, but it will be slow

**Comment by yellowbluesky** [comment]
Can you please try this build and see if it fixes your issue of broken images?

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.1.7

Note that this will create a second Muzei source called "Pixiv for Muzei 3 **_Dev_**" and you must switch to it to test the improvements.

**Comment by linsui** [comment]
It doesn't download a broken image anymore! But I can't clear the cache...

**Comment by linsui** [comment]
I find that if I enable saving to storage it stops working.

**Comment by yellowbluesky** [comment]
> It doesn't download a broken image anymore! But I can't clear the cache...

> I find that if I enable saving to storage it stops working.

This is a little odd to be honest, I do not believe I changed anything to do with file handling or the image cache clear button since my last release. 

I can still clear cache when images are saved to internal storage (option is not selected).

Before installing the fix today, what percentage of images were corrupted?

**Comment by yellowbluesky** [comment]
Since you have the fix installed for a little while now, can you please try setting saving back to internal storage (option not selected) and then let me know if clearing image cache works?

**Comment by linsui** [comment]
As long as the option is not selected, everything works well. But if I enable the option, I can't clear cache and it doesn't download new images either. I can see that it connects to pixiv and downloads something but the new image doesn't appear.

> Before installing the fix today, what percentage of images were corrupted?

About 20%?

**Comment by linsui** [comment]
It's Android 13 Lineage OS. 
[31_01-03-41-26_085.log](https://github.com/yellowbluesky/PixivforMuzei3/files/14103389/31_01-03-41-26_085.log)

**Comment by yellowbluesky** [comment]
Thanks for providing the log.. The issue looks something to do with network certificates and not with storage, which is confusing. I suspect the issue might have to do with the updated okhttp library version.

I cannot replicate the issue on my systems so I need more information.

1. Can you confirm if an authorised feed mode on the dev version (like Follow Feed) also has the same issue?

2. When you run the production version of my app from an app store (FDroid?), does it work using the same settings that cause the issue in the dev version?

**Comment by linsui** [comment]
> The issue looks something to do with network certificates and not with storage, which is confusing.

That's not related. I can reproduce the problem with a proxy. 
[31_01-15-44-34_513.log](https://github.com/yellowbluesky/PixivforMuzei3/files/14108743/31_01-15-44-34_513.log) It seems that the clear cache operation relies on downloading new images.

> Can you confirm if an authorised feed mode on the dev version (like Follow Feed) also has the same issue?

I don't have an account to test.

> When you run the production version of my app from an app store (FDroid?), does it work using the same settings that cause the issue in the dev version?

3.7 hasn't been available in F-Droid. 3.6 works well.

**Comment by yellowbluesky** [comment]
Can you please try this build and let me know if you have any issues with it.

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.1.7-alpha2

After uninstalling and reinstalling my app, I was able to replicate your issue of nto being able to save into external storage.
Turns out the issue was a very simple one and entirely my fault.

**Comment by yellowbluesky** [comment]
No worries, I'm happy to help my users :)

I'll close this issue now. When the fix gets merged into the production version on Google Play or Fdroid I will let you know here
