### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#201]
https://gitlab.com/linsui/fdroiddata/-/jobs/6078945597

```
> Task :app:minifyProdReleaseWithR8 FAILED
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/vagrant/build/com.antony.muzei.pixiv/app/build/outputs/mapping/prodRelease/missing_rules.txt.
ERROR: R8: Missing class java.lang.Module (referenced from: void okhttp3.internal.graal.OkHttpFeature.beforeAnalysis(org.graalvm.nativeimage.hosted.Feature$BeforeAnalysisAccess))
Missing class org.graalvm.nativeimage.hosted.Feature$BeforeAnalysisAccess (referenced from: void okhttp3.internal.graal.OkHttpFeature.beforeAnalysis(org.graalvm.nativeimage.hosted.Feature$BeforeAnalysisAccess))
Missing class org.graalvm.nativeimage.hosted.Feature (referenced from: okhttp3.internal.graal.OkHttpFeature)
Missing class org.graalvm.nativeimage.hosted.RuntimeResourceAccess (referenced from: void okhttp3.internal.graal.OkHttpFeature.beforeAnalysis(org.graalvm.nativeimage.hosted.Feature$BeforeAnalysisAccess))
```

Could you please take a look? Thanks!

By the way, the tag name should be 3.7.1 instead of 3.1.7.

**Comment by yellowbluesky** [comment]
The issue should be fixed with release 3.7.2. Hopefully the FDroid build works this time :)

**Comment by linsui** [comment]
Should I use 1f2448648672cef1beada902491cf9d99639b158 directly or wait for the next release?

**Comment by yellowbluesky** [comment]
Please wait for the next release, I am adding some new things as well.

I expect to be completed within 20 minutes

**Comment by yellowbluesky** [comment]
Are FDroid builds triggered manually or automatically on a new tag?

In anycase, the new release is available under tag 3.7.2 at https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/3.7.2.

Thank you for your help throughout this long running project, I really appreciate it 😄

**Comment by yellowbluesky** [comment]
never mind, retracting the release, it has issues

**Comment by linsui** [comment]
It's triggered automatically. But I want to check it ASAP. :)

**Comment by yellowbluesky** [comment]
New release is finally out and working.

Thank you for your patience :)

**Comment by linsui** [comment]
Thanks!
