### ISSUE TITLE
Support bookmark URI export.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [yellowbluesky/PixivforMuzei3#204]
As you stated you would at https://www.reddit.com/r/Pixiv/s/sBwfyRzNwJ. I've filed this because there wasn't ever a confirmation, so I don't know whether it's present.

**Comment by yellowbluesky** [comment]
Hi there,

Bookmark export functionality can be found in this release

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/experiment

I deliberately did not bring this feature to the main feature branch because I believe Pixiv will crack down on this if more users were to use it.
