### ISSUE TITLE
Can you add a mode to display liked pictures?

### ISSUE THREAD

**Issue by Aragamiz** [yellowbluesky/PixivforMuzei3#35]
other.mode useless,hope dev this new mode.thk

**Comment by yellowbluesky** [comment]
你好,你可以用中文写.我会明白一点中文,但是我不会写

The app cannot display pictures you have liked, there is no endpoint in the Pixiv API to do that unfortunately

However, the app can display images that you have bookmarked (收藏夹). Is that not an option for you?
