### ISSUE TITLE
Display photos from a search or tag.

### ISSUE THREAD

**Issue by patofet** [yellowbluesky/PixivforMuzei3#36]
I'm new to pixiv and this app and I'd like to show only "Force of Will" search images, how can I do this?
Thanks

**Comment by yellowbluesky** [comment]
Hi, there is no such functionality, however I believe I can add it

**Comment by patofet** [comment]
okey thanks ^^

**Comment by yellowbluesky** [comment]
feature added in commit 06ed0529ba4ec76f26f08fc5bed58a393414330f

to be included in app release 2.3.4
