### ISSUE TITLE
Cannot open origin 

### ISSUE THREAD

**Issue by SettingDust** [yellowbluesky/PixivforMuzei3#40]
Is there a way to open the origin page on pixiv?

**Comment by yellowbluesky** [comment]
If I understand you correctly, try clicking on the artwork title on Muzei's main screen.



![Screenshot_20191024-090902_Muzei](https://user-images.githubusercontent.com/11283778/67440550-5faf2180-f645-11e9-953e-9daee7f5c0f6.png)

**Comment by SettingDust** [comment]
Okay,, thx for your patience.
