### ISSUE TITLE
Request - option to backup downloaded images

### ISSUE THREAD

**Issue by HoloWise** [yellowbluesky/PixivforMuzei3#45]
I'd be nice to see an option for the app to save all downloaded images before removing them. It'd make my image hoarder heart happy

**Comment by yellowbluesky** [comment]
Sure, I can add this feature, should not be too hard

If I have the time I'll add it in this weekend

**Comment by yellowbluesky** [comment]
Pictures are already saved to /storage/emulated/0/Android/data/com.antony.muzei.pixiv/files/Pixtures

**Comment by HoloWise** [comment]
I know about this location but it gets periodically cleared by the app (I do have automatic 1AM cache clear TURNED OFF in options)

What I meant by this request is for the app to perhaps have an option to move the photos to a different location before it clears them but since you mentioned the folder in data, maybe 1AM cache clear is used by default even when toggle is turned off?

**Comment by yellowbluesky** [comment]
The automatic clearing despite the setting is out of my control I'm afraid; my app right now stores the images into its allocated cache folder, and Android prunes cache folders once they grow too large.

I can add a toggle to save pictures to external storage (storage that Android will not automatically clear)

Thanks for clarifying and explaining your use case

**Comment by HoloWise** [comment]
If it is like you say then option like that would be perfect.

While I don't have a lot of android dev experience from what I understand files that go above app cache quota are removed first and files below app cache quota are removed last when additional space is needed which shouldn't be the case on my device (since I keep ~2GB free in internal storage) and it seems to clear whole cache not only files that went above quota. I never saw a file that was over a day old in app's folder too. I checked it once after a few days of use and oldest was at 18 hours, the next day when I woke up folder was cleared and oldest image was 8h old and it had 20 images at max which is why I thought it's related to 1AM clear being used by default and not android clearing cache

I finally got a while to look into the code and perhaps sharedPrefs.getBoolean("pref_autoClearMode", true) returned a default because it fails to read the preference for some reason? Which btw I feel like should be defaulted to false since that's what switch is set to by default.

**Comment by yellowbluesky** [comment]
I can implement the option for you today then, I'll get out a build for you to try 

The Android docs are really opaque when it comes to cache behaviour unfortunately. Anecdotally, on my two devices

- the one with only 2GB free space is cleared fairly aggressively, about once a day if I don't have auto clear cache checked 

- the one with 102GB free space is never cleared at all

I've never seen a failure to read the preference, however you are correct and it should default to false.

**Comment by yellowbluesky** [comment]
Try this release:

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.4.0

Uninstall your current version first, then install the one linked above.

When changing modes or clearing the cache, Muzei will only show new pictures. Pictures saved into external storage will remain there, and should not be automatically cleared

**Comment by HoloWise** [comment]
Just installed it. With external storage on, clearing cache doesn't remove any pictures tho it'll take some time to fully verify since I have to wait for new daily ranking to test if it'll only show new images

Just checked directories after turning it on and fetching a few images, no pictures in /Android/data/com.antony.muzei.pixiv/files, all pictures are being saved in /Pictures/PixivForMuzei3

One odd thing I noticed is that before all this after selecting the app in Muzei it didn't fetch an image and after switching to main preview window it would rapidly iterate through various informations about art that's currently in daily ranking without showing the art itself, only after forcing it to load an image this behaviour stopped. Not sure if it's related to your app or Muzei.

Steps:
1. Uninstalled old version
2. Installed new version
3. Opened new version right after installing
4. Changed to external storage
5. Opened Muzei (Muzei was active in background and switched to default wallpaper source after uninstalling the app)
6. Changed to Pixiv, it didn't show the preview image
7. Switched to first tab with preview in Muzei
8. Info text was rapidly changing, it'd show informations about various artworks currently in daily ranking
9. Forced it to fetch an image with the double arrowhead button
10. Image loaded, odd behaviour stopped and showed informations about currently loaded image

**Comment by yellowbluesky** [comment]
Clicking the "Immediately clear cache" button should clear the images Muzei can display

Yep all files are now in /Pictures/PixivForMuzei3

The rapid iterating is normal and expected behaviour:
Muzei has its own cache storing information on the pictures my app provides (artist, title, etc), and iterates through all of them checking them when the source is first selected. It invalidates each cache entry if it sees that there's no picture file to back it.
It usually resolves itself after a few moments, but it doesn't hurt to manually force a new image.
I see it often when doing development.

Thanks for taking the time to write up your experiences :)

**Comment by HoloWise** [comment]
Everything seems to be working as intended now that the daily ranking changed and I could test clearing cache. 

One thing I noticed tho is that after clearing cache if an image that is already in the folder is also still in daily ranking, app will fetch it again and overwrite it instead of using an already existing image.

**Comment by yellowbluesky** [comment]
Feature added in 7bab93a07889092ad9d0665a47ad34e21e031f0b

Surprisingly very easy to implement, since all my pictures have consistent file extensions (png)

**Comment by HoloWise** [comment]
Ah if all pictures are saved as pngs then that's even easier lol I saw a variable with multiple file extensions and assumed those matter for the files.

Well, it's all working great so far. Thank you for implementing all of this. :)

**Comment by yellowbluesky** [comment]
Latest production version available on Google Play (2.4.2) has this feature rolled into it.

To ensure you continue to get automatic updates, uninstall the version you sideloaded, wait a short while, then install the version from Google Play
