### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#47]
Would you please publish this app on F-Droid? Thanks!

**Comment by yellowbluesky** [comment]
Hi

I can add my app to F-droid

It will likely take a short while: I'm on holiday for the next few days

**Comment by linsui** [comment]
Thanks! I'll open an RFP on F-Droid to see if there is any block.

**Comment by yellowbluesky** [comment]
Fantastic, thanks for kicking off the process for me. :smiley:

**Comment by yellowbluesky** [comment]
Has finally been merged in https://gitlab.com/fdroid/fdroiddata/-/commit/b3ea874735ceb67c586502bf5144c675ef0f9300

**Comment by linsui** [comment]
Thanks!
