### ISSUE TITLE
filter image by aspect ratio

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#51]
I'd like to get wallpaper fit my screen or only part of the image can be display. Would it be possible to filter image by aspect ratio (e.g. width:height < 1)?

**Comment by yellowbluesky** [comment]
I can add this for all modes

Whether there are enough pictures to make this option work well is another problem

**Comment by yellowbluesky** [comment]
How would you like to see this implemented?

I can add a set of two sliders, with each one controlling the minimum height/width of the artwork
Or a list of options, with the user selecting roughly what aspect ratio they want?
This one can be simplified down to three options: portrait, landscape, or both

What are your thoughts?

**Comment by linsui** [comment]
I prefer the three options. That's enough for me.

**Comment by yellowbluesky** [comment]
Hi,

Try the feature out in the build available here

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.6.0

Let me know if there are any issues or suggestions

**Comment by yellowbluesky** [comment]
Also, can I ask you to do some more translation to Simplified Chinese again?

The four words are:

- Artwork aspect ratio

- Portrait and Landscape

- Portrait

- Landscape

Thanks, I appreciate you helping out

**Comment by linsui** [comment]
Of course, I'll translate them ASAP! 😄

**Comment by linsui** [comment]
It works well for me, thanks!

**Comment by yellowbluesky** [comment]
Fantastic

One question: can I ask if you are located in China?

**Comment by linsui** [comment]
I'm in China and the SNI bypass function is convenient for me. :smile:
