### ISSUE TITLE
reverse NSFW filter option

### ISSUE THREAD

**Issue by linsui** [yellowbluesky/PixivforMuzei3#52]
Could you please add an option showing only higher NSFW filtering level images?

**Comment by yellowbluesky** [comment]
This should be easy to do.

I'm thinking of a checkbox list, with the user selecting what NSFW levels they want

**Comment by linsui** [comment]
Good idea. Thanks!

**Comment by yellowbluesky** [comment]
#53

**Comment by yellowbluesky** [comment]
Feature has been added.

To test download at https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.5.0 

To install, uninstall any version that you may have installed from the Play Store.

**Comment by yellowbluesky** [comment]
Hi, try it out now
It can be found at https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.5.1

**Comment by linsui** [comment]
Looks good to me! Thanks!

**Comment by yellowbluesky** [comment]
#55
