### ISSUE TITLE
App doesn't download images (custom rom)

### ISSUE THREAD

**Issue by HoloWise** [yellowbluesky/PixivforMuzei3#62]
Hi, recently I moved from galaxy a5 2016 (stock) to Xiaomi Redmi Note 4X with custom ROM (Pixel Experience - Android 10)

Sadly the app now seems to not be able to download any images (After selecting it in Muzei nothing happens). Dahlia's pixiv app works just fine so it's nothing related to Muzei itself. I tried version 2.6.1 (from play store) and 2.4.5 (from github) and both had the same issue.

---EDIT---
I just saw issue #49 and after doing what NarihiroCH did in his last comment app does work. I'm going to test it a bit more.

After allowing NSFW art app still downloads images (gallery gets bigger)

After ticking auto cache clear at 1AM app still downloads images (gallery gets bigger)

After ticking external storage app seems to not download any images (gallery size stays the same)

After disabling external storage app downloads images once more (galley gets bigger, I also cleared cache just to see if it redownloads old images)

At this point I went to check storage permissions and Pixiv for Muzei did have storage permissions but Muzei itself did not (and never asked for them but i allowed storage permissions manually, it didn't help anyway)

I enabled external storage again and cleared cache. After loading next image in Muzei it showed M logo for a while, then started iterating through informations about images only to later disable next image button, gallery has one image inside that doesn't get set as wallpaper even if I press it (Muzei states it did set it as wallpaper). I checked it again few minutes later and there was a new image that ended up being empty with some pixiv info attached to it. Seems like gallery slowly fills up with those empty images over time now. Muzei still has the next image button disabled, double click doesn't do anything.

Seems like there's an issue with external storage option (Android 10? or maybe just some specific roms?)

---Edit2--- 

I turned off external storage and 1am cache clear, cleared cache manually, app still doesn't download anything, button is gone, gallery is still full of empty images. 

I reinstalled Muzei and Pixiv for Muzei, enabled 1am wipe and NSFW. Works fine, I disables 1am wipe. Works fine. Seems like if it starts to fill gallery with empty images that only have info attached it completely bricks Pixiv for Muzei.

**Comment by yellowbluesky** [comment]
Wow, you've done some very thorough investigation, I commend you for that :)

Did you do all your testing with "Daily Ranking" update mode?

Unfortunately I have not done any testing on any actual Android 10 hardware (this will change soon), only on the emulator where it seems to work

Since you're on a custom ROM, and probably have root access, can I get you to do a very quick logcat trace for me? This will massively help me figure out the issue.

**Comment by yellowbluesky** [comment]
https://github.com/yellowbluesky/PixivforMuzei3/issues/63

**Comment by HoloWise** [comment]
Here's logcat I did on a working version of muzei after fresh install with some artworks already loaded

https://pastebin.com/Lvr4h2yz

1. opened muzei
2. went to pixiv for muzei settings
3. Enabled nsfw, 1am clear and storage
4. Loaded images a few times, app broken as before

**Comment by yellowbluesky** [comment]
Thanks for providing me with a logcat

It's an issue with storing into external storage

`01-24 00:39:12.337 26274 27281 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Pictures/PixivForMuzei3/79013886.png: open failed: EACCES (Permission denied)`

**Comment by yellowbluesky** [comment]
Can you confirm that all of the login update modes (feed, bookmark, etc) work, if you have external storage setting not checked?

**Comment by HoloWise** [comment]
I checked feed, bookmark, recommended, monthly and weekly with external storage unchecked and all worked fine. I left the app on recommended, checked external storage and cleared cache, app broke.

App does ask me for storage permission when I check external storage and after checking in android settings, Pixiv for Muzei is allowed to access storage.

Thank you for working on the fix ^^

**Comment by HoloWise** [comment]
Hey I thought I'd leave one more comment about all that. I decided to test it a bit more with other apps namely Twitter, Reddit and Sankaku White.

All 3 apps were granted storage rights and I confirmed that in android settings, all 3 wanted to write to /storage/emulated/0/Pictures in their respective folders by default. Reddit and Twitter were able to create their own folders and write files to them but Sankaku didn't have permissions to create the folder, I created it manually and then it couldn't write files there. Luckily Sankaku allows users to pick exact directory on their own so I hand picked the exact same directory it couldn't write to. System file app asked me if I want to give the app permissions to this specific folder. I allowed it. From that point app works fine and downloads images to the folder it wanted to create but failed without manual selection.

**Comment by yellowbluesky** [comment]
Hi,

I'm making good progress. I've tested it on an Android 10 emulator, images are indeed getting saved to external storage, it works.

What I still need to do is to pass to Muzei the path to those downloaded images.

I'm going to sleep now, I'll very likely have something for you tomorrow

**Comment by yellowbluesky** [comment]
Hi,

Try this build

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.6.3

**Comment by HoloWise** [comment]
This version works perfect with external storage on ^^

**Comment by yellowbluesky** [comment]
Fantastic, thanks you were very helpful
