### ISSUE TITLE
Duplicate artworks downloaded to external storage

### ISSUE THREAD

**Issue by HoloWise** [yellowbluesky/PixivforMuzei3#66]
It's me again :P 

I just noticed that the app has issues with downloading and fills the folder with duplicates. Can't really tell when it started because before moving to a new phone  (running 2.6.3 rn) I was running 2.4.2 without upgrading due to a lack of space.

Auto cache clear turned on, external storage turned on.

Example of an artwork that got downloaded multiple times. 
![Screenshot_20200130-154444](https://user-images.githubusercontent.com/36460595/73460235-6fdb4900-4378-11ea-9af5-5be621c53e98.png)

![Screenshot_20200130-155342](https://user-images.githubusercontent.com/36460595/73460538-f2fc9f00-4378-11ea-843b-ee29267ca416.png)
![Screenshot_20200130-155407](https://user-images.githubusercontent.com/36460595/73460542-f5f78f80-4378-11ea-8f3b-69b4fa2c4f95.png)
![Screenshot_20200130-155432](https://user-images.githubusercontent.com/36460595/73460552-f8f28000-4378-11ea-9bc2-250e73020743.png)

**Comment by yellowbluesky** [comment]
Hi, again too :)

Thanks for your report, it's a regression introduced when I added Android 10 support.

It'll likely be a number of days before I can get out a fix, I'm going on a short trip over the weekend

**Comment by HoloWise** [comment]
Take your time and enjoy your trip :D

**Comment by yellowbluesky** [comment]
Construct a cursor to traverse the MediaStore ContentResolver.

`SELECT * FROM MediaStore.Images.Media.EXTERNAL_CONTENT_URI WHERE DISPLAY_NAME = filename AND RELATIVE_PATH = Pictures/PixivForMuzei3`

If the cursor is returned with a count of greater than 0 then there is a duplicate, and do not proceed with storing into external storage

**Comment by yellowbluesky** [comment]
You're in luck

The fix was easier to implement than I through

Try it out here https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.6.5

If you're coming from an installation from the Play Store, uninstall that first before installing this

**Comment by HoloWise** [comment]
I just installed a new version ~ half an hour ago so I'll let you know if there are any issues in connection with duplicates if I see any but so far it's good.

There's one more issue that I just noticed tho idk if I should make a new issue thread or write it here. Some of the images dating all the way back to 2.4.2 release when I started using the app are corrupted and the most recent case was right before I moved to 2.6.5. Seems like downloading just randomly cuts off and the app writes all the data to a file anyway and treats it as a proper image. In a sample of 1244 images it happened ~12 times.

For example this file has 127KB and cuts off at address 0x0001FF80 while it should be 490KB and should stop at address 0x0007AA20

https://www.pixiv.net/en/artworks/79153001

![79153001](https://user-images.githubusercontent.com/36460595/73538732-07e63a80-442c-11ea-8dd9-5966d1add554.jpg)

**Comment by yellowbluesky** [comment]
I've seen the issue before, but the rarity at which it occurs makes it very hard to pinpoint a definite cause.

I'm suspecting network issues.

To be honest, the low rate at it happening (less than 1% for you) makes this a bit of a low priority for me

**Comment by HoloWise** [comment]
It's not that big of a deal for me anyway I can just list the ids and pass them through PixivUtil if I really want those artworks :P 

Good news, 11 hours and no duplicates so original issue seems to be resolved.

**Comment by yellowbluesky** [comment]
Fantastic, thanks
