### ISSUE TITLE
It is not work since 18 February suddenly

### ISSUE THREAD

**Issue by dingyinghu** [yellowbluesky/PixivforMuzei3#77]
Since yesterday afternoon, the software will not update the pictures. I tried some measures.

1.click the next button, it didn't work and the button disappeared
2.reboot the phone
3.reinstall app, incloud Muzei and Pixiv for Muzei

 All of these didn't work anymore.
So i try change to other source from play store, such as Bing or pixel art and original source,and it can update pictures.
In addition, pixiv account cannot be logged in now.
I'm not sure if it's just me?
Maybe because I'm in China?
![Screenshot_2020-02-19-10-46-38-162_net nurik roman muzei](https://user-images.githubusercontent.com/32993902/74797053-35285900-5305-11ea-91a2-3d00ab0cc979.png)

![Screenshot_2020-02-19-10-46-55-905_com antony muzei pixiv](https://user-images.githubusercontent.com/32993902/74797059-3a85a380-5305-11ea-8030-0ca81eef6c26.png)

**Comment by dingyinghu** [comment]
![Screenshot_2020-02-19-10-48-15-535_com android settings](https://user-images.githubusercontent.com/32993902/74797330-d2838d00-5305-11ea-9e09-709fe5606017.png)

**Comment by yellowbluesky** [comment]
Hi there,

I am having no issues (Australia), I'm very sorry to hear you're having problems

I last published an app update to the Play store 10 days ago; an app update is not the cause of your problem

I believe the problem to be related to your location in China.
I can test this now, I can get a VPN which will give me a Chinese IP Address.

Give me a day or two to investigate

**Comment by dingyinghu** [comment]
In fact, I have changed my position to Hongkong or America through VPN,but it didn't work.I realize that you've done some extra work to make sure the app works in China without VPN.I don't know how did it work. Maybe it has some problems now?

**Comment by Cibo444** [comment]
i got same problem，it doesn't work since yesterday

**Comment by yellowbluesky** [comment]
Tomorrow is the weekend, I will have more time to sit down and try to understand this issue. I'll try to get out a fix before Sunday

**Comment by dingyinghu** [comment]
Thank you for your reply！
I am sorry for that if it affect your pace of life.

**Comment by yellowbluesky** [comment]
I've identified a problem; Pixiv had changed their API endpoints.

I will fix the immediate problem, but also investigate ways to make my app more robust

Expect a build in a short while

**Comment by yellowbluesky** [comment]
Hi everyone,

Can I get you guys to test this build for me?

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.7.3

To install this, uninstall any version that you may have installed from the Play Store

The change was that Pixiv had changed the thumbnail URL for their ranking images. 

- Previously I was using the thumbnail URL as a base, modifying it give me a URL for a high resolution image. As such when Pixiv changed the thumbnail URL, my high resolution URLs broke

- The high resolution URL remains unchanged. Now I buildmy own high resolution URL that takes attributes from the thumbnail URL as necessary. This is a more robust way of doing things, and should lead to fewer problems.

**Comment by dingyinghu** [comment]
It works!
I do some test .

     1.Everything works fine if i open VPN.
     2.Without VPN, it doesn't update the picture and can't log in.
     3.the changes in VPN status（open to close,i mean） will cause the app to not update picture whatever i open the vpn or not after that. I must change the rank model and Muzei source to make app reset(or clear all the data of app),and it will work as point 1 said.

It's not a problem for me because I keep the vpn connected all the time.

If you still need to do a test, please tell me

 Thanks a lot for your hard work!

**Comment by yellowbluesky** [comment]
Nice to see that it works for you

I still have some work to do, I would my app to work in China without using a VPN

**Comment by dingyinghu** [comment]
Now there seems to be a new bug.

The function of sharing pictures is not working properly.
In the picture I uploaded, the number 0 is the next wallpaper to be switched, the number 1 is my current wallpaper, and the number 2、3 or 4 is the wallpaper i used before.
And now only the NO.0 picture can be shared. When other pictures are shared to social app, they show that the picture does not exist.
![-64cfab8288a60121](https://user-images.githubusercontent.com/32993902/75105581-27017200-5650-11ea-8b5a-1a10710d18fb.jpg)

**Comment by panyuhang93** [comment]
please let me

**Comment by yellowbluesky** [comment]
Thanks for offering your help

If you haven't already, download the build from here

https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.7.4

and let me know how it works for you. If it's good I'll re-enable the app for distribution in China

**Comment by dingyinghu** [comment]
It works perfectly!
I didn't find bug anymore.

It can work without VPN.I try to switch the VPN and have no effect to it.

Thanks a lot！

**Comment by panyuhang93** [comment]
![Screenshot_20200226-101937_Gmail.png](https://i.loli.net/2020/02/26/zZm9nswv6dp21DE.png)
![Screenshot_20200226-101927_Muzei.png](https://i.loli.net/2020/02/26/B6uKahGcE5dlwVJ.png)
work without vpn,perfect!

**Comment by yellowbluesky** [comment]
Ok, thanks a lot for your help guys :D

I'll push this build out for distribution in China

**Comment by yellowbluesky** [comment]
Hey everyone,

I've pushed the update with all the features and fixes rolled into 2.7.5 onto the Google Play Store. Thanks for all your help in submitting the reports and trialling the builds.

To install the version from the Google Play Store, first uninstall any version you may have installed from here.
