### ISSUE TITLE
Sharing images does not work reliably in 2.7.3

### ISSUE THREAD

**Issue by yellowbluesky** [yellowbluesky/PixivforMuzei3#79]
Now there seems to be a new bug.

The function of sharing pictures is not working properly.
In the picture I uploaded, the number 0 is the next wallpaper to be switched, the number 1 is my current wallpaper, and the number 2、3 or 4 is the wallpaper i used before.
And now only the NO.0 picture can be shared. When other pictures are shared to social app, they show that the picture does not exist.
![-64cfab8288a60121](https://user-images.githubusercontent.com/32993902/75105581-27017200-5650-11ea-8b5a-1a10710d18fb.jpg)

_Originally posted by @dingyinghu in https://github.com/yellowbluesky/PixivforMuzei3/issues/77#issuecomment-590035239_

**Comment by yellowbluesky** [comment]
@dingyinghu

**Comment by yellowbluesky** [comment]
Thank you for reporting this issue

This was a regression introduced in 2.7.2, to do with the improvements I made to file extension handling.

**Comment by yellowbluesky** [comment]
https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.7.4

Hi, try this release for a fix to the issue sharing

**Comment by dingyinghu** [comment]
In terms of the current test results, the sharing function works perfectly.
That's help me a lot.
Thank you!

**Comment by yellowbluesky** [comment]
You're very welcome :)
